using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductApi.Entities;

/// <summary>
///     Entité de produit
/// </summary>
public class Product
{
    /// <summary>
    ///     Id de l'entité, généré automatiquement par la base de données
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Id is generated by DB, but can be set for seeding/testing
    public int Id { get; set; }

    /// <summary>
    ///     Nom du produit
    /// </summary>
    /// <example>Produit 1</example>
    [StringLength(100)]
    public required string Name { get; set; }

    /// <summary>
    ///     Prix du produit ne peut pas être négatif
    /// </summary>
    [Range(0, double.MaxValue)]
    public required decimal Price { get; set; }

    /// <summary>
    ///     Stock disponible pour le produit
    /// </summary>
    [Range(0, int.MaxValue)]
    public required int Stock { get; set; }

    /// <summary>
    ///     Slug du produit, utilisé pour l'URL
    /// </summary>
    /// <example>produit-1</example>
    [StringLength(100)]
    public required string Slug { get; set; } // Slug is generated, but needs a setter for EF tracking

    /// <summary>
    ///     Description du produit
    /// </summary>
    /// <example>Ceci est une description</example>
    [StringLength(255)]
    public string? Description { get; init; }

    /// <summary>
    ///     Date de création du produit en base
    /// </summary>
    public DateOnly CreatedAt { get; set; } // Should be set on creation, but needs setter for EF tracking

    /// <summary>
    ///     Date de maj du produit en base
    /// </summary>
    public DateOnly? UpdatedAt { get; set; } // Should be set on update, but needs setter for EF tracking

    /// <summary>
    /// Indique si le produit est périssable (impacte les conditions de retour)
    /// </summary>
    public bool IsPerishable { get; set; } = false; // Par défaut, non périssable
}
